"""

Revision ID: 341610a0c1af
Revises: 
Create Date: 2025-08-30 13:15:51.023945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '341610a0c1af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###