"""

Revision ID: 7d427339ef32
Revises: 341610a0c1af
Create Date: 2025-08-30 19:45:38.086056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d427339ef32'
down_revision = '341610a0c1af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('receive_notifications', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'receive_notifications')
    # ### end Alembic commands ###